Ecommerce/Ecommerce/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq' if defined?(Sidekiq) && defined?(Sidekiq::Web)

  if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything', to: proc { [404, {}, ['']] }, constraints: lambda { |request|
                                                                     !request.path_parameters[:anything].start_with?('rails/')
                                                                   }
    end
  end
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'signup' },
             controllers: { registrations: 'users/registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '/:locale' do
    devise_scope :user do
      get 'users', to: 'devise/sessions#new'
      get 'login', to: 'devise/sessions#new'
      get 'register', to: 'devise/registrations#new'
      get 'logout', to: 'devise/sessions#destroy'
      get 'users/carts', to: 'carts#index'
      get 'users/checkout_vnpay', to: 'checkouts#index'
      get 'users/checkout_vnpay/pay', to: 'checkouts#create'
    end
    get 'product_details/index'
    get 'product-details/:id', to: 'product_details#index'
    get 'category/:id', to: 'categories#categories'
    get 'contact', to: 'contact#index'
    post 'contact', to: 'contact#create'
    get 'brand/:id', to: 'brand#brands'
    get 'blog', to: 'blog#index'
    get 'blog_detail/:id', to: 'blog#blog_detail'
    get 'blog_category/:id', to: 'blog#blog_category'
    get 'users/orders', to: 'orders#index'
    get 'users/loves', to: 'loves#index'
    get 'users/history_product', to: 'product_view#index'
    get 'notification/:id', to: 'notification#index'
    get 'admin/system', to: 'notification#index'
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/category', to: 'categories#index'
      post '/love', to: 'loves#index'
      post '/comment', to: 'loves#comment'
      post '/rate', to: 'loves#rate'
      post '/checkout', to: 'carts#checkout'
      post '/checkout_with_momo', to: 'carts#payment_momo'
      get '/checkout_success', to: 'carts#success'

      delete '/unlove', to: 'loves#unlove'
      post 'edit-comment', to: 'loves#edit_comment'
      post 'edit-comment-children', to: 'loves#edit_comment_children'
      delete 'delete-comment-children', to: 'loves#delete_comment_children'

      delete '/delete-comment', to: 'loves#delete_comment'
      post 'reply-comment', to: 'loves#reply_comment'
      post '/product', to: 'products#products_of_month'
      post '/search', to: 'products#search'
      post '/voucher', to: 'products#voucher'
      post '/delete_order', to: 'products#delete_order'
      post '/search_blog', to: 'blogs#search'
      get '/load_more_product', to: 'products#more_product'
      get '/load-more-comment', to: 'loves#more_comment'
      get '/quick-review', to: 'products#quick_review'
    end
  end
end

Ecommerce/Ecommerce/app/views/layouts/_footer.html.erb
<footer id="footer">
  <!--Footer-->
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="companyinfo">
            <h2>Mr.Katsu </h2>
            <p><%= t 'description_mrkatsu_footer' %></p>
          </div>
        </div>
        <div class="col-sm-7">
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag '/assets/home/iframe3.png' , alt:"img" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2022</h2>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag '/assets/home/iframe2.png' , alt:"img" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2022</h2>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag '/assets/home/iframe3.png' , alt:"img" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2022</h2>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag '/assets/home/iframe4.png' , alt:"img" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2022</h2>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="address">
            <img src="/assets/home/map.png" alt="" />
            <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-widget">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>
              <%= t 'service' %>
            </h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">
                  <%= t 'Online_Help' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Contact_Us' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Order_Status' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Change_Location' %>
                </a></li>
              <li><a href="#">FAQ’s</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>
              <%= t 'quock_shop' %>
            </h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">T-Shirt</a></li>
              <li><a href="#">
                  <%= t 'Mens' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Womans' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Gift_Cards' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Shoes' %>
                </a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>
              <%= t 'policies' %>
            </h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">
                  <%= t 'Terms_of_Use' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Privecy_Policy' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Refund_Policy' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Billing_System' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Ticket_System' %>
                </a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>
              <%= t 'about_mrkatsu' %>
            </h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">
                  <%= t 'Company_Information' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Careers' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Store_Location' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Affillate_Program' %>
                </a></li>
              <li><a href="#">
                  <%= t 'Copyright' %>
                </a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <div class="single-widget">
            <h2>
              <%= t 'about_mrkatsu' %>
            </h2>
            <form action="#" class="searchform">
              <input type="text" placeholder="Your email address" />
              <button type="submit" class="btn btn-default"><i
									class="fa fa-arrow-circle-o-right"></i></button>
              <p><%= t 'description_update_site' %></p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <p class="pull-left">Copyright © 2021 MR.Katsu Inc. All rights reserved.</p>
        <p class="pull-right">
          <%= t 'Designed' %> <span><a target="_blank" href="#">Trần Hữu Thắng</a></span>
        </p>
      </div>
    </div>
  </div>
</footer>
<!--/Footer-->

Ecommerce/Ecommerce/app/views/layouts/_header.html.erb
<header id="header">
  <!--header-->
  <div class="header_top">
    <!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li><a href="#"><i class="fa fa-phone"></i> +84 7296 4842</a></li>
              <li><a href="#"><i class="fa fa-envelope"></i> tranhuuthangcoi@gmail.com</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="social-icons pull-right">
            <ul class="nav navbar-nav">
              <li><a href="https://www.facebook.com/thangneymar44"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header_top-->
  <div class="header-middle">
    <!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-md-4 clearfix" style=" display: flex; justify-content: center;">
          <div class="logo pull-left">
            <a href="/"><img src="/assets/home/logo.png" width="150" alt="" /></a>
          </div>
        </div>
        <div class="col-md-8 clearfix" id="menu-list">
          <div class="shop-menu clearfix pull-right">
            <ul class="nav navbar-nav">
              <li><a href="/profile"><i class="fa fa-user"></i>
                  <%= t 'menu.account' %>
                </a></li>
              <li class="notifications" style="padding-right: 10px;" onclick="myFunction()">
                <a href="javascript:void(0);"> <i class="fa fa-bell" style="font-size:15px"></i>
                  <%= t 'menu.notification' %>
                  <div class="icon-badge"></div>
                </a>
                <ul id="list-notifications" style="display: none">
                  <% if current_user %>
                    <% @results[:notifications].each do |item| %>
                      <li class="item-notification">🔔 <a
													href="/<%=I18n.locale %>/notification/<%= item.title.parameterize%>~<%=item.id%>">
                          <%= item.title %>
                        </a></li>
                    <% end %>
                  <% end %>
                </ul>
              </li>
              <li><a href="<%= users_carts_path %>"><i class="fa fa-crosshairs"></i>
                  <%= t 'menu.checkout' %>
                </a></li>
              <li style="cursor: pointer;"><a onclick="location.href='<%= users_carts_path %>'">
                  <%= t 'menu.cart' %> <i class="fa fa-shopping-cart"></i> <span
											class='badge badge-warning' id='lblCartCount'> </span>
                </a></li>
              <% if user_signed_in? %>
                <% if current_user.admin? %>
                  <li><a href="/admin?locale=en"><i class="fa fa-lock"></i>
                      <%= current_user.username %>
                    </a></li>
                <% else %>
                  <li><a href="<%= edit_user_registration_path %>"><i class="fa fa-lock"></i>
                      <%= current_user.username %>
                    </a></li>
                <% end %>
                <li><a href="/<%=I18n.locale %>/logout"><i class="fa fa-lock"></i>
                    <%= t 'action.logout' %>
                  </a></li>
              <% else %>
                <li><a href="<%= new_user_session_path %>"><i class="fa fa-lock"></i>
                    <%= t 'action.login' %>
                  </a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-middle-->
  <div class="header-bottom">
    <!--header-bottom-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
							data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a href="<%= root_path %>" class="active">
                  <%= t 'menu.home' %>
                </a></li>
              <li class="dropdown"><a href="#">
                  <%= t 'menu.shop' %><i class="fa fa-angle-down"></i>
                </a>
                <ul role="menu" class="sub-menu">
                  <li><a href="/profile">
                      <%t 'menu.profile' %>
                    </a></li>
                  <li><a href="<%= users_carts_path %>">
                      <%= t 'menu.checkout' %>
                    </a></li>
                  <li><a href="<%= users_carts_path %>">
                      <%= t 'menu.cart' %>
                    </a></li>
                  <li><a href="<%= login_path %>">
                      <%= t 'action.login' %>
                    </a></li>
                  <li><a href="<%= contact_path %>">
                      <%= t 'menu.contact' %>
                    </a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#">
                  <%= t 'blog' %><i class="fa fa-angle-down"></i>
                </a>
                <ul role="menu" class="sub-menu">
                  <li><a href="<%= blog_path %>">
                      <%= t 'blog_list' %>
                    </a></li>
                </ul>
              </li>
              <li><a href="<%= contact_path %>">
                  <%= t 'menu.contact' %>
                </a></li>
              <% if user_signed_in? %>
                <li><a href="<%= users_orders_path %>">
                    <%= t "menu.my_orders" %>
                  </a></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="col-sm-3" style="display: flex;
						flex-direction: column;
						justify-content: center;
						align-items: center;">
          <span style="font-size: 15px">
            <%= t("languages")%>
          </span>
          <%= link_to "English 🇬🇧" , locale:"en" %>
          <%= link_to "Vietnamese 🇻🇳" , locale:"vi" %>
          <!-- <div class="custom-select" style="width:200px;">
						<select id="Choice_i18n">
						  <option value="0">Select city:</option>
						<option value="1">English</option>
						 <option value="2">Vietnamese</option>
						</select>
					</div> -->
          <div class="search_box pull-right">
            <input class="in-search" id="search-product" data-autocomplete-source="<%= Product.order("title").map(&:title)%>" type="text" style="color: #000; font-weight: 700;" placeholder="<%= t "product.search" %>"/>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-bottom-->
</header>
<!--/header-->
<style>
  #list-notifications {
  	height: auto;
  	width: 300px;
  	position: absolute;
  	-moz-box-shadow: 3px 3px 5px 6px #ccc;
  	-webkit-box-shadow: 3px 3px 5px 6px #ccc;
  	box-shadow: 2px 2px 4px 2px #ccc;
  	padding-left: 1px;
  }

  #list-notifications>li {
  	width: 100%;
  	border: 1px solid #ebebeb
  }
</style>
<script>
  $(document).off().on("click", ".navbar-toggle",function(e) {
  	 $(this).attr("show-dropdown", true)
  });
  function myFunction() {
  	var x = document.getElementById("list-notifications");
  	if (x.style.display === "none") {
  		x.style.display = "block";
  	} else {
  		x.style.display = "none";
  	}
  }

    $( function() {
      $( "#search-product" ).autocomplete({
        maxResults: 5,
        minLength: 2,
        source:  function(request, response) {
        var results = $.ui.autocomplete.filter( $("#search-product").data("autocomplete-source"), request.term);
        response(results.slice(0, this.options.maxResults));
        } ,
      });
    });
</script>

Ecommerce/Ecommerce/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home | Mr.Katsu</title>
    <meta id="metaDescription" name="description" content="Trần Hữu Thắng, shop mr.katsu, buy everything your need">
    <meta property="og:description" content="Trần Hữu Thắng, shop mr.katsu, shopmrkatsu.tk, shopmrkatsu" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://shopmrkatsu.tk/" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'bootstrap.min' %>
    <%= javascript_include_tag 'jquery-filterable' %>
    <link rel="shortcut icon" href="/assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1"></script>
    <%=javascript_include_tag('frontend/categories.js') %>
    <%=stylesheet_link_tag('price-range.css') %>
    <%=stylesheet_link_tag('font-awesome.min.css') %>
    <%=stylesheet_link_tag('animate.css') %>
    <%=javascript_include_tag('jquery.js') %>
    <%=javascript_include_tag('bootstrap.min.js') %>
    <%=javascript_include_tag('jquery.scrollUp.min.js') %>
    <%=javascript_include_tag('jquery.prettyPhoto.js') %>
    <%=javascript_include_tag('manager/product.js') %>
    <%=javascript_include_tag('manager/cart.js') %>
    <%=javascript_include_tag('manager/blog.js') %>
    <%=javascript_include_tag('lightbox.min.js') %>
    <%=stylesheet_link_tag('lightbox.min.css') %>
    <%=javascript_include_tag('handlerbar.js') %>
    <%=javascript_include_tag('query.ez-plus.js') %>
    <%=javascript_include_tag('chartkick.min.js') %>
    <%=javascript_include_tag('jquery.cookie.js') %>
    <%=stylesheet_link_tag('slick.css') %>
    <%=javascript_include_tag('slick.min.js') %>
    <%=javascript_include_tag('jquery.ui.js') %>
    <%=javascript_include_tag('register-compare-handlebar.js') %>
    <%=javascript_include_tag('lodash.min.js') %>
  </head>
  <body>
    <!-- LOADER -->
    <%= render 'layouts/header' %>
    <% if notice%>
      <div id="notice_wraper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif flash %>
      <% flash.each do |message_type, message| %>
        <div  style="align-items: center;text-align: center;background: #e8a62d59;color: red;" class="alert alert-<%= message_type %>"><span><%= message %></span></div>
      <% end %>
    <% end %>
    <div id="loader" style="display: flex;justify-content: center;align-items: center;">
      <div class="position-center-center">
        <div class="ldr"></div>
      </div>
    </div>
    <div class="show_body" style="display:none">
      <script>
        $("#loader").fadeOut("slow");
        $(".show_body").css("display","block")
      </script>
      <!-- Modal -->
      <div class="modal fade product-details"  id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      </div>
      <%= yield %>
      <script>
        setTimeout(function() {
          $('#notice_wraper').fadeOut("slow", function () {
            $(this).remove();
          });
        }, 2000);
      </script>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v13.0&appId=219816340114971&autoLogAppEvents=1" nonce="WK7rdaIn"></script>
<!-- Messenger Plugin chat Code -->
<div id="fb-root"></div>
<!-- Your Plugin chat code -->
<div id="fb-customer-chat" class="fb-customerchat">
</div>
<script>
  var chatbox = document.getElementById('fb-customer-chat');
  chatbox.setAttribute("page_id", "2741635706062292");
  chatbox.setAttribute("attribution", "biz_inbox");
</script>
<!-- Your SDK code -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      xfbml            : true,
      version          : 'v12.0'
    });
  };

  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
<script id="list-search-template" type="text/x-handlebars-template">
  <div class="features_items">
    <h2 class="title text-center"> Result search for {{keyword}}</h2>
    {{#if products.length }}
      {{#each products}}
      <div class="col-sm-4 col-xs-6">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <input type="hidden" id="{{id}}" class="id" value="{{id}}">
                    <a href="/<%=I18n.locale %>/product-details/{{title}}~{{id}}"> <img class="imageProduct" src="{{image_url1}}" alt="" /></a>
                    <h2 class="price">${{price}}</h2>
                    <p class="title">{{title}}</p>
                </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="/<%=I18n.locale %>/product-details/{{title}}~{{id}}"><i class="fa fa-plus-square"></i><%= t 'loadMore.text' %></a></li>
                    <li><a href="javascript:void(0)" class="quick_view"  product-id= "{{id}}>" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-plus-square"></i> <%= t 'quick_view.text' %></a></li>
                </ul>
            </div>
        </div>
      </div>
      {{/each}}
    </div>
  {{else}}
    <div class="features_items">
      <h2 style=" text-align: center;"> <%= t("messages.search_product") %></h2>
    </div>
  {{/if}}
</script>
<!-- Messenger Plugin chat Code -->
<script id="list-detail-quick-review-template" type="text/x-handlebars-template">
  {{#if products }}
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" style="display:none">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%= t'product.detail' %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div style="text-align: center">
            <div id="load" style="display:block">
              <img src="//s.svgbox.net/loaders.svg?fill=maroon&ic=tail-spin"
                  style="width:24px">
            </div>
        </div>
       <div class="">
            <div class="img-review col-sm-5" >
            <div class="view-product">
                <img id="zoom_01" class="imageProduct" src="{{products.image_url}}" alt="">
                    <a href="{{products.image_url}}" rel="prettyPhoto" id="image-review"  class="zoom-image">
                    <h3>ZOOM</h3>
                </a>
            </div>
        <div id="similar-product" class="carousel slide" data-ride="carousel">

            <!-- Wrapper for slides -->
            <div class="carousel-inner">

                <div class="item active">
                </div>

                <div class="item">
                </div>
            </div>

                <!-- Controls -->
            </div>
        </div>
        <div class="col-sm-7">
            <div class="product-information ">
                <!--/product-information-->
                <input type="hidden" id="{{products.id}}" class="id" value="">
                <img src="/assets/product-details/new.jpg" class="newarrival" alt="">
                <h2 style="text-align: center" class="title">{{products.name}}</h2>
                <div class="list-rate">
                </div>
                  <div style="display: flex; justify-content: center; cursor: pointer;">
                      <span style="margin-right: 10px" class="fa fa-star" id="star-1"></span>
                      <span style="margin-right: 10px" class="fa fa-star" id="star-2"></span>
                      <span style="margin-right: 10px" class="fa fa-star" id="star-3"></span>
                      <span style="margin-right: 10px" class="fa fa-star" id="star-4"></span>
                      <span style="margin-right: 10px" class="fa fa-star" id="star-5"></span>
                        <span>({{products.avg}}/5)</span>

                  </div>

                <span class="product_love" style="text-align: center">
                        <i class="fa fa-heart" id="hear-f" onclick="return confirm('You must be logged in to perform this function')"></i>
                </span>

                <span>
                    <span style="text-align: center; width: 100%" class="price">USD ${{products.price}}
                          {{#when products.price_old 'gt' 0 }}
                            <del class="price_old">${{products.price_old}}</del>
                          {{else}}
                            <del class="price_old"></del>
                          {{/when}}
                      </span>

                    <label style="font-size:15px">Quantity:</label>
                    <input type="number" name= "my-input" id="numberInput" class="quantity" value="1" min="1" max="{{products.number_intock}}">
                       {{#when products.number_instock 'gt' 0 }}
                        <button type="submit" class="btn btn-fefault cart add-to-cart-detail">
                            <i class="fa fa-shopping-cart"></i>
                            <%= t 'product.add_to_cart' %>
                        </button>
                        {{else}}
                          <button type="submit" class="btn btn-danger">
                                <i class="fa fa-shopping-cart"></i>
                                <%= t 'product.out_of_stock' %>:
                          </button>
                        {{/when}}
                </span>
                <div>
                <span style="font-size:15px"> <b> <%= t 'product.choose_size' %> </b> </span>

                  <div class="sprd-select__items">
                    {{#each products.size}}
                      {{#when @index 'eq' 0}}
                            <div class="button active">{{this}} </div>
                        {{/when}}
                        {{#when @index 'gt' 0}}
                            <div class="button ">{{this}} </div>
                        {{/when}}
                    {{/each}}
                  </div>
                </div>
                <p><b>Availability:</b> {{products.availability}}</p>
                <p><b>Number instock:</b>  {{products.number_instock}}</p>
                <p><b>Status:</b>  {{products.status}}</p>
                <p><b>Brands:</b> {{products.brand}}</p>
                <p><b>Views: </b> {{products.views}} <i class="fa fa-eye"></i></p>
                <p><b>Share:</b> <a href="https://www.facebook.com/share.php?u=http://shopmrkatsu.tk/en/product-details/shirt~1"><i class="fa fa-facebook-square fa-2x facebook" style="font-size: 1.5em;"></i></a></p>
            </div>
            <!--/product-information-->
        </div>
     </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" style="margin-top: -15px;" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
    {{else}}
    <div style="text-align: center">
          <button class="load_more spinner-border btn btn-warning" style="margin: 0 auto; background-color: #fe980f; margin-bottom: 15px;" data-style="expand-left"  ><%= t 'loadMore.text' %></button>
          <div id="load" style="display:none">
            <img src="//s.svgbox.net/loaders.svg?fill=maroon&ic=tail-spin"
                style="width:24px">
          </div>
          <%# <%= paginate @results[:features_items], theme: 'twitter-bootstrap-4'  %>
    </div>
  {{/if}}
</script>